### ISSUE TITLE
Please explain plugin usefulness

### ISSUE THREAD

**Issue by pcav** [RuizGeo/Sampling#1]
The functionality described in the About seems already present in core QGIS.
Please clarify what the plugin is actually adding.
Sorry for bothering, but we are trying hard not to duplicate functionality, so to reduce confusion for the users and administrative burden.
Thanks.

**Comment by RuizGeo** [comment]
Modify descrition: description=Sampling calculates rasters statistics and assigns them to shapefiles. The user informs the rasters and shapfiles folder. All files within the folder are used in the process, this automates statistical sampling for multiple files.
